ALTER TABLE "addresses" DROP CONSTRAINT fk_user, ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE "products" DROP CONSTRAINT fk_store, ADD CONSTRAINT fk_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE;